export const config = {
    projectId: String(import.meta.env.VITE_APPWRITE_PROJECT_ID),
    projectName: String(import.meta.env.VITE_APPWRITE_PROJECT_NAME),
    appwriteEndpoint: String(import.meta.env.VITE_APPWRITE_ENDPOINT),
    bucketId: String(import.meta.env.VITE_APPWRITE_BUCKET_ID),
    databaseId: String(import.meta.env.VITE_APPWRITE_DATABASE_ID),
    tableId: String(import.meta.env.VITE_APPWRITE_TABLE_ID),
    apiKey: String(import.meta.env.APPWRITE_API_KEY),
    usersCollectionId: String(import.meta.env.VITE_APPWRITE_USERS_COLLECTION_ID),
    clubRequestsCollectionId: String(import.meta.env.VITE_APPWRITE_CLUB_REQUESTS_COLLECTION_ID),
    clubsCollectionId: String(import.meta.env.VITE_APPWRITE_CLUBS_COLLECTION_ID),
    clubMembersCollectionId: String(import.meta.env.VITE_APPWRITE_CLUB_MEMBERS_COLLECTION_ID),
    joinRequestsCollectionId: String(import.meta.env.VITE_APPWRITE_JOIN_REQUESTS_COLLECTION_ID),
    postsCollectionId: String(import.meta.env.VITE_APPWRITE_POSTS_COLLECTION_ID),
    registrationsCollectionId: String(import.meta.env.VITE_APPWRITE_REGISTRATIONS_COLLECTION_ID),
    rteApiKey: String(import.meta.env.VITE_RTE_API_KEY),
}